#!/bin/bash
output_file="./scripts/errors/out_ablation.txt"

> "$output_file"

run_command() {
  local cmd="$1"
  echo "Running: $cmd"
  eval "$cmd" || (echo "Command failed, capturing output..." && eval "$cmd >> $output_file 2>&1")
}

cancer_type=$(echo "${data_name::-3}" | tr '[:lower:]' '[:upper:]')

# Baseline
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,cnv,pro --selected_features --slide_aggregation early --pooling avgpoolto1 --target_nb_patches 5 15 25  --run_name baseline"

# Different Inputs
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,cnv,pro --slide_aggregation early --pooling avgpoolto1 --target_nb_patches 5 15 25  --run_name omics_full"
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics dna,cnv,pro --selected_features --slide_aggregation early --pooling avgpoolto1 --target_nb_patches 5 15 25  --run_name omics_norna"
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,cnv,pro --selected_features --slide_aggregation early --pooling avgpoolto1 --target_nb_patches 5 15 25  --run_name omics_nodna"
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,pro --selected_features --slide_aggregation early --pooling avgpoolto1 --target_nb_patches 5 15 25  --run_name omics_nocnv"
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,cnv --selected_features --slide_aggregation early --pooling avgpoolto1 --target_nb_patches 5 15 25  --run_name omics_nopro"
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion concat --mlp_depth 1 --slide_aggregation early --pooling avgpoolto1 --target_nb_patches 5 15 25  --run_name omics_wsi"

# Slide aggregation
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,cnv,pro --selected_features --slide_aggregation late --pooling avgpoolto1 --target_nb_patches 5 15 25  --run_name agg_late"
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,cnv,pro --selected_features --slide_aggregation mid --pooling avgpoolto1 --target_nb_patches 5 15 25  --run_name agg_mid"

# Cluster sizes
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,cnv,pro --selected_features --slide_aggregation early --pooling avgpoolto1 --target_nb_patches 1 --run_name clust_1"
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,cnv,pro --selected_features --slide_aggregation early --pooling avgpoolto1 --target_nb_patches 5 25 --run_name clust_double"
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,cnv,pro --selected_features --slide_aggregation early --pooling avgpoolto1 --target_nb_patches 5 25 100 --run_name clust_wide"
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,cnv,pro --selected_features --slide_aggregation early --pooling avgpoolto1 --target_nb_patches 3 7 10 --run_name clust_narrow"

# Cluster pooling
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,cnv,pro --selected_features --slide_aggregation early --pooling padortruncate --target_nb_patches 5 15 25  --run_name pool_port"
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,cnv,pro --selected_features --slide_aggregation early --pooling avgpooltomin --target_nb_patches 5 15 25  --run_name pool_avgmin"
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,cnv,pro --selected_features --slide_aggregation early --pooling maxpoolto1 --target_nb_patches 5 15 25  --run_name pool_max1"
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,cnv,pro --selected_features --slide_aggregation early --pooling maxpooltomin --target_nb_patches 5 15 25  --run_name pool_maxmin"

# Continuous-time survival
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,cnv,pro --selected_features --slide_aggregation early --pooling avgpoolto1 --target_nb_patches 5 15 25  --run_name cont8 --surv_model cont --accumulation_steps 8"
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,cnv,pro --selected_features --slide_aggregation early --pooling avgpoolto1 --target_nb_patches 5 15 25  --run_name cont16 --surv_model cont --accumulation_steps 16"
run_command "CUDA_VISIBLE_DEVICES=0 python main.py --coords_dir /media/nfs/SURV/$cancer_type/SP1024/patches/ --feats_dir /media/nfs/SURV/$cancer_type/Feats1024/CONCH/ --data_name $data_name --results_dir ./results/ablation/$data_name --early_stopping 15 --gc 32 --lambda_reg 0.0001 --reg 0.0001 --lr 0.0002 --lr_patience 7 --max_epochs 20 --model_type spact --embedding_dim 128 --ff 2 --fusion bilinear --mlp_depth 1 --omics rna,dna,cnv,pro --selected_features --slide_aggregation early --pooling avgpoolto1 --target_nb_patches 5 15 25  --run_name cont32 --surv_model cont --accumulation_steps 32"

python ./scripts/check_errors.py "$output_file"
